name: Deploy to Cloud Run

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write   # REQUIRED for Workload Identity

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    # 1️⃣ Authenticate to GCP and get ACCESS TOKEN
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: "projects/655119496782/locations/global/workloadIdentityPools/github-pool/providers/github-provider-final"
        service_account: "github-cloudrun-sa@vertex-ai-learning-480916.iam.gserviceaccount.com"
        token_format: "access_token"

    # 2️⃣ Login Docker explicitly using access token (THIS WAS MISSING)
    - name: Docker login to Artifact Registry
      run: |
        echo "${{ steps.auth.outputs.access_token }}" | \
        docker login -u oauth2accesstoken --password-stdin \
        https://us-central1-docker.pkg.dev

    # 3️⃣ Build & Push image
    - name: Build & Push Docker Image
      run: |
        docker build \
          -t us-central1-docker.pkg.dev/vertex-ai-learning-480916/rag-repo/rag-api:latest \
          -f deployment/Dockerfile \
          deployment
        docker push us-central1-docker.pkg.dev/vertex-ai-learning-480916/rag-repo/rag-api:latest

    # 4️⃣ Deploy to Cloud Run
    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy rag-api \
          --image us-central1-docker.pkg.dev/vertex-ai-learning-480916/rag-repo/rag-api:latest \
          --region us-central1 \
          --platform managed \
          --allow-unauthenticated \
          --memory 4Gi \
          --cpu 2
